apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: gn-enriched-data-couchbase-source
  labels:
    strimzi.io/cluster: quickplay1-cluster
spec:
  class: com.couchbase.connect.kafka.CouchbaseSourceConnector
  tasksMax: 1
  config:
    couchbase.topic: gn-enriched-data-topic
    couchbase.seed.nodes: "cb1.product-stag.firstlight.ai,cb2.product-stag.firstlight.ai,cb3.product-stag.firstlight.ai"
    couchbase.bootstrap.timeout: 20s
    couchbase.bucket: gn-enriched-data
    couchbase.username: kafkasource
    couchbase.password: kafkasource
    couchbase.source.handler: com.couchbase.connect.kafka.handler.source.DefaultSchemaSourceHandler
    couchbase.event.filter: com.couchbase.connect.kafka.filter.AllPassFilter
    couchbase.stream.from: NOW
    couchbase.compression: ENABLED
    couchbase.flow.control.buffer: 128m
    couchbase.persistence.polling.interval: 100ms
