apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: ${{ env.CLUSTER_NAME }}-cluster
  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  image: ${{ env.CONNECT_IMAGE_URL }}
  version: 3.7.0
  replicas: 1
  bootstrapServers: ${{ env.CLUSTER_NAME }}-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: ${{ env.CLUSTER_NAME }}-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    producer.max.request.size: 10485880
    consumer.max.request.size: 10485880
    socket.request.max.bytes: 104857600
    socket.send.buffer.bytes: 10485760
    socket.receive.buffer.bytes: 10485760
    message.max.bytes: 10485760
    max.partition.fetch.bytes: 10485760
    socket.request.max.bytes: 104857600
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nodepool
                  operator: In
                  values:
                  - tools
