apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: aggregator-data-couchbase-source
  labels:
    strimzi.io/cluster: ${{ env.CLUSTER_NAME }}-cluster
spec:
  class: com.couchbase.connect.kafka.CouchbaseSourceConnector
  tasksMax: 1
  config:
    couchbase.topic: aggregator-data-snowflake-topic
    couchbase.seed.nodes: cb1.api.cms.amdvids.local,cb2.api.cms.amdvids.local,cb3.api.cms.amdvids.local
    couchbase.bootstrap.timeout: 20s
    couchbase.bucket: aggregator-data
    couchbase.username: kafkasource
    couchbase.password: kafkasource
    couchbase.source.handler: com.couchbase.connect.kafka.handler.source.DefaultSchemaSourceHandler
    couchbase.event.filter: com.couchbase.connect.kafka.filter.AllPassFilter
    couchbase.stream.from: NOW
    couchbase.compression: ENABLED
    couchbase.flow.control.buffer: 128m
    couchbase.persistence.polling.interval: 100ms
