apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ${{ env.CLUSTER_NAME }}
spec:
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
      producer.max.request.size: 10485880
      consumer.max.request.size: 10485880
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 10485760
      socket.receive.buffer.bytes: 10485760
      message.max.bytes: 10485760
      max.partition.fetch.bytes: 10485760
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1000Gi
        deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: ${{ env.NODEPOOL_K8S_LABLE_KEY }}
                    operator: In
                    values:
                    - ${{ env.NODEPOOL_K8S_LABEL_VALUE }}
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1000Gi
      deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: ${{ env.NODEPOOL_K8S_LABLE_KEY }}
                    operator: In
                    values:
                    - ${{ env.NODEPOOL_K8S_LABEL_VALUE }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: ${{ env.NODEPOOL_K8S_LABLE_KEY }}
                    operator: In
                    values:
                    - ${{ env.NODEPOOL_K8S_LABEL_VALUE }}