apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ${{ env.CLUSTER_NAME }}
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
      producer.max.request.size: 10485880
      consumer.max.request.size: 10485880
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 10485760
      socket.receive.buffer.bytes: 10485760
      message.max.bytes: 10485760
      max.partition.fetch.bytes: 10485760
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 500Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 500Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
